#    Copyright (C) 2005-2007 Ruben Moreno Montoliu <ruben3d@gmail.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

################################################################################
#                                                                              #
# Makefile.config                                                              #
#                                                                              #
# User configurable parameters for the building proccess.                      #
#                                                                              #
################################################################################


################################################################################

# Project directory structure

################################################################################

# Base directory of the project (all the relative paths are concatenated with
# this path).
#PROJECT_PATH=../..
PROJECT_PATH=$(shell pwd)/../..

# Directory where final binary files are placed.
BIN_PATH=bin

# Directory where temporary object files and dependencies are stored.
BUILD_PATH=build

# Directory with the source code.
SRC_PATH=src

# Directory where the documentation is generated and stored.
DOC_PATH=doc

# Directory where the distribution is generated.
DIST_PATH=dist

# In this directory all the data used by the application is stored. The 'bin'
# target uses this directory as workpath and all its contents are copied into
# the basedir of the distribution.
DATA_PATH=data


################################################################################

# File names

################################################################################

# Name of the final executable file.
TARGET=raytrace

# Name of the Doxygen configuration file.
DOXYFILE=Doxyfile

# Name of the compressed file where the distribution is stored (.tar.gz is
# automatically appended).
DISTFILE=$(TARGET)_`date +%Y%m%d_%H%M`


################################################################################

# Additional resources

################################################################################

# Additional source directories under SRC_PATH.
SRC_SUBDIRS=app core gui io math scene examples

# Files to be excluded from the building proccess.
EXCLUDE=

# Additional static libraries to be linked
STATICS=

# Additional shared libraries to be linked.
LIBS=boost_system boost_thread SDL png12

# Path for additional includes (header files not included into a source
# directory).
INC=

# Additional paths with Makefiles to be executed.
MAKEFILE_PATHS=


################################################################################

# Generation options

################################################################################

# Builds an static library instead of an executable binay.
GENERATE_STATIC_LIBRARY=no

# Removes all the symbol information from the binary.
STRIP_TARGET=no

# Name of the doxygen application (in order to generate documentation).
DOXYGEN=doxygen
